name: James Pickett
description: Personal Website
menu:
 - page: Research
   url: /research
   links:
    - title: "Polymaths of Islam"
      url: "#polymaths-of-islam"
    - title: "Russian Subject, Muslim Monarch"
      url: "#russian-subject-muslim-monarch"
    - title: "Seeing like a Princely State"
      url: "#seeing-like-a-princely-state"
    - title: "Side Projects"
      url: "#side-projects"
 - page: Teaching
   url: /teaching
   links:
    - title: "Courses"
      url: "#courses"
    - title: "For Students"
      url: "#current-and-prospective-students"
 - page: Graduate Advising
   url: /graduate
   links:
    - title: "FAQ"
      url: "#doctoral_training_history"
menu_external:
 - title: Pitt History Department
   url: "http://www.history.pitt.edu/people/james-pickett"
 - title: Academia.edu
   url: "https://pitt.academia.edu/JamesPickett"
 - title: GitHub
   url: "https://github.com/pickettj"
 - title: Bactriana
   url: "https://bactriana.org"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: "jamespickett.info"
locale: en_GB
