name: James Pickett
description: Personal Website
menu:
 - page: Research
   url: /research
   links:
    - title: "Polymaths of Islam"
      url: "#polymaths-of-islam"
    - title: "Seeing like a Princely State"
      url: "#seeing-like-a-princely-state"
    - title: "Side Projects"
      url: "#side-projects"
 - page: Teaching
   url: /teaching
 - page: Graduate Advising
   url: /graduate
menu_external:
 - title: Department Website
   url: "http://www.history.pitt.edu/people/james-pickett"
 - title: Academia.edu
   url: "https://pitt.academia.edu/JamesPickett"
 - title: Twitter
   url: "https://twitter.com/pickettzoda"
 - title: GitHub
   url: "https://github.com/pickettj"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: "jamespickett.info"
locale: en_GB
